/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;
import module.dto.UserDTO;

/**
 *
 * @author Admin
 */
public class winMain extends javax.swing.JFrame {

    /**
     * Creates new form winMain
     */
    public winMain() {
        setModule(null);
        initComponents();
    }
    public winMain(UserDTO user) {
        JOptionPane.showMessageDialog(this, "welcome "+ user.getEmail());
        setModule(user);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniLogout = new javax.swing.JMenuItem();
        mniClose = new javax.swing.JMenuItem();
        mniUser = new javax.swing.JMenu();
        mniUserMN = new javax.swing.JMenuItem();
        mniRequestCreate = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniRequestMN = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 1500));

        jMenu1.setText("File");

        mniLogout.setText("Logout");
        mniLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mniLogout);

        mniClose.setText("Close");
        jMenu1.add(mniClose);

        jMenuBar1.add(jMenu1);

        mniUser.setText("User");

        mniUserMN.setText("UserManage");
        mniUserMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUserMNActionPerformed(evt);
            }
        });
        mniUser.add(mniUserMN);

        mniRequestCreate.setText("Create Request");
        mniUser.add(mniRequestCreate);

        jMenuBar1.add(mniUser);

        jMenu2.setText("Admin");

        mniRequestMN.setSelected(true);
        mniRequestMN.setText("requestMN");
        jMenu2.add(mniRequestMN);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Employee");

        jMenuItem3.setText("employeeMN");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("department");

        jMenuItem1.setText("departmentMN");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniLogoutActionPerformed

    private void mniUserMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUserMNActionPerformed
        // TODO add your handling code here:
        ifrUserMN userMN = new ifrUserMN();
        userMN.setVisible(true);
        this.add(userMN);
    }//GEN-LAST:event_mniUserMNActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ifrDepartment department = new ifrDepartment();
        department.setVisible(true);
        this.add(department);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ifrEmployee empMN = new ifrEmployee();
        empMN.setVisible(true);
        this.add(empMN);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    private void setModule(UserDTO user){
        this.setSize(1000, 1000);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(winMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(winMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(winMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(winMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new winMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mniClose;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenuItem mniRequestCreate;
    private javax.swing.JCheckBoxMenuItem mniRequestMN;
    private javax.swing.JMenu mniUser;
    private javax.swing.JMenuItem mniUserMN;
    // End of variables declaration//GEN-END:variables
}
